# Generated by Django 6.0.2 on 2026-05-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='profile/default.jpg', upload_to='profile/')),
                ('title', models.CharField(default='About Me', max_length=100)),
                ('intro', models.TextField()),
                ('description', models.TextField()),
                ('resume_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(default='Pakistan', max_length=100)),
                ('availability_text', models.CharField(default='Open to Freelance', max_length=100)),
                ('projects_status', models.CharField(default='Available for Projects', max_length=100)),
                ('profile_status', models.CharField(default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AboutCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Ready to Build?', max_length=100)),
                ('heading', models.CharField(default="Let's work on something worth building.", max_length=255)),
                ('highlighted_text', models.CharField(default='worth building.', max_length=255)),
                ('subheading', models.TextField()),
                ('primary_button_text', models.CharField(default='Start a Project', max_length=50)),
                ('primary_button_link', models.CharField(default='/freelance/', max_length=255)),
                ('secondary_button_text', models.CharField(default='Send a Message', max_length=50)),
                ('secondary_button_link', models.CharField(default='/contact/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(default='+', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Your full name (e.g. Muhammad Ahmad)', max_length=100)),
                ('tagline', models.CharField(help_text='Your short title or tagline (e.g. Full Stack Developer | UI/UX Enthusiast)', max_length=200)),
                ('hero_image', models.ImageField(default='profile/default.jpg', help_text='Profile image for hero section', upload_to='profile/')),
                ('about_heading', models.CharField(default='About Me', help_text='Heading shown above About section preview', max_length=100)),
                ('about_short_description', models.TextField(help_text="Short paragraph displayed on the home page in 'About Me' section")),
                ('work_button_text', models.CharField(default='View My Work', max_length=50)),
                ('contact_button_text', models.CharField(default='Contact Me', max_length=50)),
                ('contact_preview_heading', models.CharField(default='Let’s Connect', max_length=100)),
                ('contact_preview_text', models.TextField(help_text='Short paragraph shown before the Contact button at the end')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Basic Info',
                'verbose_name_plural': 'Basic Info',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('problem', models.TextField()),
                ('approach', models.TextField()),
                ('tech_decisions', models.TextField()),
                ('outcome', models.TextField()),
                ('lessons_learned', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('github', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('subject', models.CharField(max_length=150)),
                ('project_type', models.CharField(choices=[('web', 'Web Application'), ('saas', 'SaaS Platform'), ('ai', 'AI Integration'), ('automation', 'Automation / Bots'), ('ecommerce', 'E-Commerce'), ('dashboard', 'Dashboard / CMS'), ('api', 'Backend / API'), ('mvp', 'MVP / Prototype'), ('student', 'Student Project'), ('other', 'Other / Not Sure')], default='other', max_length=30)),
                ('budget', models.CharField(blank=True, choices=[('under-500', '< $500'), ('500-1500', '$500–1.5k'), ('1500-5000', '$1.5k–5k'), ('5000-plus', '$5k+'), ('discuss', "Let's Talk"), ('not-sure', 'Not Sure')], max_length=30, null=True)),
                ('timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('replied', 'Replied'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='portfolio_contact_form', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_score', models.PositiveIntegerField(default=0, help_text='Internal score for lead quality.')),
                ('conversion_probability', models.PositiveIntegerField(default=0, help_text='Estimated probability of conversion (0-100).')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated project value.', max_digits=12, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Internal tags like startup, urgent, high-budget.')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Assigned admin/team member.', max_length=120, null=True)),
                ('internal_priority_notes', models.TextField(blank=True, null=True)),
                ('is_hot_lead', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('client_budget_estimate', models.CharField(blank=True, max_length=120, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('communication_history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi bi-star-fill', max_length=100)),
                ('icon_bg', models.CharField(default='rgba(59,130,246,0.1)', max_length=50)),
                ('icon_color', models.CharField(default='var(--accent)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('year_range', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('year_range', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('pricing', 'Pricing'), ('workflow', 'Workflow'), ('legal', 'Legal'), ('general', 'General')], default='general', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('limited', 'Taking Limited Work')], default='available', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated technologies, e.g. Django, Bootstrap, MySQL', max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('experimental', 'Experimental')], default='in_progress', max_length=20)),
                ('category', models.CharField(choices=[('fullstack', 'Full Stack'), ('django', 'Django'), ('ai', 'AI / ML'), ('automation', 'Automation'), ('ecommerce', 'E-commerce'), ('productivity', 'Productivity'), ('game', 'Game'), ('other', 'Other')], default='fullstack', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('website', 'Website Development'), ('django', 'Django Web App'), ('ecommerce', 'E-commerce Store'), ('automation', 'Automation Script'), ('ai', 'AI Integration'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Bootstrap icon class', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SummarySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#007BFF', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
                ('proficiency', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='tech_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('feedback', models.TextField()),
                ('stars', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tools/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=220)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Quote')], default='fixed', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('revisions', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_custom_quote', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.service')),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_features', to='core.servicepackage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
