# Generated by Django 6.0.2 on 2026-05-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='projectinquiry',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='projectinquiry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectinquiry',
            name='project_type',
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='inquiries/files/'),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='full_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='selected_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicepackage'),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='source',
            field=models.CharField(choices=[('contact_page', 'Contact Page'), ('services_page', 'Services Page'), ('package_page', 'Package Page'), ('landing_page', 'Landing Page'), ('direct', 'Direct')], default='contact_page', max_length=50),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('discovery', 'Discovery Call'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='timeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='budget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
