# Generated by Django 6.0.2 on 2026-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_projectinquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project Inquiry', 'verbose_name_plural': 'Project Inquiries'},
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Assigned admin/team member.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='client_budget_estimate',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='communication_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='conversion_probability',
            field=models.PositiveIntegerField(default=0, help_text='Estimated probability of conversion (0-100).'),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='internal_priority_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='is_hot_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='lead_score',
            field=models.PositiveIntegerField(default=0, help_text='Internal score for lead quality.'),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web Application'), ('saas', 'SaaS Platform'), ('ai', 'AI Integration'), ('automation', 'Automation / Bots'), ('ecommerce', 'E-Commerce'), ('dashboard', 'Dashboard / CMS'), ('api', 'Backend / API'), ('mvp', 'MVP / Prototype'), ('student', 'Student Project'), ('other', 'Other / Not Sure')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Internal tags like startup, urgent, high-budget.'),
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='budget',
            field=models.CharField(blank=True, choices=[('under-500', '< $500'), ('500-1500', '$500–1.5k'), ('1500-5000', '$1.5k–5k'), ('5000-plus', '$5k+'), ('discuss', "Let's Talk"), ('not-sure', 'Not Sure')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated project value.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='source',
            field=models.CharField(choices=[('contact_page', 'Contact Page'), ('services_page', 'Services Page'), ('package_page', 'Package Page'), ('landing_page', 'Landing Page'), ('portfolio_page', 'Portfolio Page'), ('case_study_page', 'Case Study Page'), ('direct', 'Direct'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('other', 'Other')], default='contact_page', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('qualified', 'Qualified'), ('discovery', 'Discovery Call'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('in_progress', 'In Progress'), ('won', 'Won'), ('lost', 'Lost'), ('completed', 'Completed'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=30),
        ),
    ]
