# Generated by Django 5.2.4 on 2025-10-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Your full name (e.g. Muhammad Ahmad)', max_length=100)),
                ('tagline', models.CharField(help_text='Your short title or tagline (e.g. Full Stack Developer | UI/UX Enthusiast)', max_length=200)),
                ('hero_image', models.ImageField(default='profile/default.jpg', help_text='Profile image for hero section', upload_to='profile/')),
                ('about_heading', models.CharField(default='About Me', help_text='Heading shown above About section preview', max_length=100)),
                ('about_short_description', models.TextField(help_text="Short paragraph displayed on the home page in 'About Me' section")),
                ('work_button_text', models.CharField(default='View My Work', max_length=50)),
                ('contact_button_text', models.CharField(default='Contact Me', max_length=50)),
                ('contact_preview_heading', models.CharField(default='Let’s Connect', max_length=100)),
                ('contact_preview_text', models.TextField(help_text='Short paragraph shown before the Contact button at the end')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Basic Info',
                'verbose_name_plural': 'Basic Info',
            },
        ),
    ]
