# Generated by Django 6.0.2 on 2026-05-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.OneToOneField(blank=True, help_text='Link this project to its case study', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ref', to='core.casestudy'),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower = shown first. Controls card order.'),
        ),
        migrations.AddField(
            model_name='project',
            name='performance_note',
            field=models.CharField(blank=True, help_text="Short metric shown in the metrics row, e.g. '99% Uptime'", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='users_count',
            field=models.CharField(blank=True, help_text="Display string, e.g. '1,200+'", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('fullstack', 'Full Stack'), ('django', 'Django'), ('ai', 'AI / ML'), ('automation', 'Automation'), ('ecommerce', 'E-commerce'), ('productivity', 'Productivity'), ('game', 'Game'), ('other', 'Other')], default='fullstack', help_text='Shown as the card category label', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(db_column='featured', default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('experimental', 'Experimental')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated, e.g. Django, Bootstrap, MySQL', max_length=255),
        ),
    ]
