# Generated by Django 6.0.2 on 2026-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('turnaround', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('fullstack', 'Full Stack'), ('django', 'Django'), ('ai', 'AI / ML'), ('automation', 'Automation'), ('ecommerce', 'E-commerce'), ('productivity', 'Productivity'), ('game', 'Game'), ('other', 'Other')], default='fullstack', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('experimental', 'Experimental')], default='in_progress', max_length=20),
        ),
    ]
