# Generated by Django 6.0.2 on 2026-05-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('problem', models.TextField()),
                ('approach', models.TextField()),
                ('tech_decisions', models.TextField()),
                ('outcome', models.TextField()),
                ('lessons_learned', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('website', 'Website Development'), ('django', 'Django Web App'), ('ecommerce', 'E-commerce Store'), ('automation', 'Automation Script'), ('ai', 'AI Integration'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='freelancestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('pricing', 'Pricing'), ('workflow', 'Workflow'), ('legal', 'Legal'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
