# Generated by Django 6.0.2 on 2026-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_casestudy_projectinquiry_freelancestatus_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Ready to Build?', max_length=100)),
                ('heading', models.CharField(default="Let's work on something worth building.", max_length=255)),
                ('highlighted_text', models.CharField(default='worth building.', max_length=255)),
                ('subheading', models.TextField()),
                ('primary_button_text', models.CharField(default='Start a Project', max_length=50)),
                ('primary_button_link', models.CharField(default='/freelance/', max_length=255)),
                ('secondary_button_text', models.CharField(default='Send a Message', max_length=50)),
                ('secondary_button_link', models.CharField(default='/contact/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(default='+', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='about',
            name='availability_text',
            field=models.CharField(default='Open to Freelance', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='profile_status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='projects_status',
            field=models.CharField(default='Available for Projects', max_length=100),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='icon_bg',
            field=models.CharField(default='rgba(59,130,246,0.1)', max_length=50),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='icon_class',
            field=models.CharField(default='bi bi-star-fill', max_length=100),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='icon_color',
            field=models.CharField(default='var(--accent)', max_length=50),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5),
        ),
    ]
